### ISSUE TITLE
Error Line 289 when trying to load plugin (Maya 2019)

### ISSUE THREAD

**Issue by ryanreptoid** [matiascodesal/maya-glTF#12] opened 2019-03-29 18:41 UTC
Can't load the plugin in Maya 2019. I get this error when I try:
`// Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/pluginWin.mel line 289:  (glTFExport) // 
// Warning: file: C:/Program Files/Autodesk/Maya2019/scripts/others/pluginWin.mel line 289: No initializePlugin() or initializePlugin2() function`

**Comment by WillemvdPijl** [comment] 2019-05-01 09:54
I am currently getting the exact same error.

**Comment by matiascodesal** [comment] 2019-07-07 22:01
Hey guys.  Thanks for opening this issue.  I was not able to reproduce this on Maya 2019 for Windows ( Cut ID: 201812112215).  Some things we can try to gather more info might be:

Can you load the plugin with this MEL command?  If not, what's the error in the script editor:
`loadPlugin "glTFTranslator"`

Does running an export via Python only work?  Here's a Python test to run:
`import glTFExport   
glTFExport.export(r"C:\Temp\test.glb", resource_format='bin', anim='keyed', vflip=True)`

**Comment by matiascodesal** [comment] 2019-07-08 00:36
Hey @ryanreptoid and @WillemvdPijl.  Thanks for opening this issue.  I was not able to reproduce this on Maya 2019 for Windows ( Cut ID: 201812112215).  

Make sure you followed the instructions correctly in the README for installing the plugin.  If you are trying to browse to the plugin through the Plug-In Manager, then make sure you are loading the glTFTranslator.py and NOT glTFExport.py.  That was the only way I was able to reproduce that error you pasted into your comment.

If it's still not working, some things we can try to gather more info might be:

Can you load the plugin with this MEL command?  If not, what's the error in the script editor:
`loadPlugin "glTFTranslator"`

Does running an export via Python only work?  Here's a Python test to run:
`import glTFExport   
glTFExport.export(r"C:\Temp\test.glb", resource_format='bin', anim='keyed', vflip=True)`

**Comment by matiascodesal** [comment] 2019-07-28 01:10
I'm pretty sure this was user error trying to load the plugin.  Closing for now.  Please reopen if this is still a problem.

**Closed by matiascodesal** 2019-07-28 01:10 UTC
Labels: question, user informed

**Comment by Euphoria1215** [comment] 2022-12-08 09:14
Warning: file: E:/Autodesk/Maya2019/scripts/others/pluginWin.mel line 910: Could not load E:/Autodesk/Maya2019/plug-ins/mtoa/2019/plug-ins/mtoa.mll as a plug-in //

**Comment by Euphoria1215** [comment] 2022-12-08 09:15
Warning: file: E:/Autodesk/Maya2019/scripts/others/pluginWin.mel line 910: Could not load E:/Autodesk/Maya2019/plug-ins/mtoa/2019/plug-ins/mtoa.mll as a plug-in // 
when i tring to load mtoa.mll , it has this warning,wish for help
